FROM nginx:latest
COPY index.html /usr/share/nginx/html/index.html
COPY app.js /usr/share/nginx/html/app.js
COPY styles.css /usr/share/nginx/html/styles.css
COPY favicon.ico /usr/share/nginx/html/favicon.ico
EXPOSE 80
