services:
  backend:
    build: .
    ports:
      - "8081:8080"
    networks:
      - shared-network
    depends_on:
      - postgres
      - rabbitmq

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - shared-network
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    networks:
      - shared-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"   # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management plugin port
    networks:
      - shared-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq

networks:
  shared-network:
    external: true

volumes:
  postgres-data:
  rabbitmq_data:
  rabbitmq_logs:
