services:
  backend:
    build: .
    ports:
      - 8081:8080
    networks:
      - app-network
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - 80:80
    networks:
      - app-network
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - 5433:5433
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
