spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration # temporary fix
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password
  ocr:
    temp-folder: /tmp/ocr/
  data:
    elasticsearch:
      client:
        connection-timeout: 10s
        socket-timeout: 5s
      rest:
        uris: http://elasticsearch:9200
      repositories:
        enabled: true
