version: '3.8'
services:

  worker-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker-service
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: password

networks:
  swkom_app-network:
    external: true
