services:
  worker-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker-service
    ports:
      - "8080:8080"
    networks:
      - shared-network
    depends_on:
      - elasticsearch
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: user
      SPRING_RABBITMQ_PASSWORD: password
      MINIO_ENDPOINT: http://minio-main:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET_NAME: documents

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
