services:
  worker-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker-service
    ports:
      - "8080:8080"
    networks:
      - shared-network
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    container_name: elasticsearch
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
